apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
        - name: vue-app
          image: ghcr.io/claudioccj/vue-app:3f7ca965e35c97a40d975e88527efd22205040e7
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      imagePullSecrets:
        - name: ghcr-secret
