apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
        - name: vue-app
          image: ghcr.io/claudioccj/vue-app:1fd1de1d1298a949d8d72dc13d865b4b92b09479
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      imagePullSecrets:
        - name: ghcr-secret
