apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
        - name: vue-app
          image: ghcr.io/claudioccj/vue-app:774dd56c9d1056fa1ccc80704dbc01079f0ce175
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      imagePullSecrets:
        - name: ghcr-secret
